[package]
name = "lavaxemu-core"
version.workspace = true
edition.workspace = true
description = "Platform-independent LavaX virtual machine"
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
bincode.workspace = true
crc32fast.workspace = true
log.workspace = true
encoding_rs.workspace = true
unifont.workspace = true
